-- MySQL Script generated by MySQL Workbench
-- Wed Dec 16 15:45:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ROLE` ;

CREATE TABLE IF NOT EXISTS `ROLE` (
  `id_role` INT NOT NULL,
  `nazev` VARCHAR(45) NOT NULL,
  `vaha` INT NOT NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UZIVATEL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UZIVATEL` ;

CREATE TABLE IF NOT EXISTS `UZIVATEL` (
  `id_uzivatel` INT NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  `ROLE_id_role` INT NOT NULL,
  `heslo` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_uzivatel`),
  INDEX `fk_UZIVATEL_ROLE_idx` (`ROLE_id_role` ASC) VISIBLE,
  CONSTRAINT `fk_UZIVATEL_ROLE`
    FOREIGN KEY (`ROLE_id_role`)
    REFERENCES `ROLE` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRISPEVEK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PRISPEVEK` ;

CREATE TABLE IF NOT EXISTS `PRISPEVEK` (
  `id_prispevek` INT NOT NULL AUTO_INCREMENT,
  `datum` DATE NOT NULL,
  `nadpis` VARCHAR(60) NOT NULL,
  `text` TEXT NOT NULL,
  `id_recenzent` INT NULL,
  `recenzovano` INT NOT NULL,
  `UZIVATEL_id_uzivatel` INT NOT NULL,
  PRIMARY KEY (`id_prispevek`),
  INDEX `fk_PRISPEVEK_UZIVATEL1_idx` (`UZIVATEL_id_uzivatel` ASC) VISIBLE,
  CONSTRAINT `fk_PRISPEVEK_UZIVATEL1`
    FOREIGN KEY (`UZIVATEL_id_uzivatel`)
    REFERENCES `UZIVATEL` (`id_uzivatel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ROLE`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `ROLE` (`id_role`, `nazev`, `vaha`) VALUES (0, 'čtenář', 0);
INSERT INTO `ROLE` (`id_role`, `nazev`, `vaha`) VALUES (1, 'autor', 1);
INSERT INTO `ROLE` (`id_role`, `nazev`, `vaha`) VALUES (2, 'recenzent', 2);
INSERT INTO `ROLE` (`id_role`, `nazev`, `vaha`) VALUES (3, 'administrátor', 3);

COMMIT;

